# Generated by Django 3.2.8 on 2021-12-06 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_doc_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
    ]
