# Generated by Django 3.2.8 on 2021-12-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentupload_document_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentupload',
            old_name='document_id',
            new_name='document',
        ),
    ]
