# Generated by Django 3.2.8 on 2021-12-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_rename_document_id_documentupload_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentupload',
            old_name='document',
            new_name='document_id',
        ),
    ]
